<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Exercice require</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body>
        <?php require "header.phtml"; ?>
        <?php
            if($route === "home")
            {
                require "home.phtml";
            }
            else if($route === "about")
            {
                require "about.phtml";
            }
            else if($route === "contact")
            {
                require "contact.phtml";
            }
            else
            {
                require "home.phtml";
            }
        ?>
        <?php require "footer.phtml"; ?>
    </body>
</html>