<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Formulaire CV</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap">
    <link rel="stylesheet" href="style.css" />

</head>
<body>
    <form action="index.php" method="post">


        <label for="cvColor">Couleur du CV:</label>
        <select name="cvColor" id="cvColor">
            <option value="blue">Bleu</option>
            <option value="red">Rouge</option>
        </select>

        <input type="submit" value="Créer CV">
    </form>
</body>
</html>